### ISSUE TITLE
fits_cut method ignoring output_dir argument

### ISSUE THREAD

**Issue by hickst** [spacetelescope/astrocut#20] opened 2019-10-28 05:27 UTC
The `astrocut.fits_cut` method fails to write the cutout file to the directory specified by the `output_dir` argument. Instead the cutout file *always* appears to be written **to the directory from which the image was read**. A sample test file is attached which demonstrates this (sadly renamed as a '.txt' file to fool stupid GitHub attachment checks).

[test_fits_output.py.txt](https://github.com/spacetelescope/astrocut/files/3777219/test_fits_output.py.txt)

Below is the output from a successful test run. Note that the line:
```
OUTPUT_DIR=/tmp/outdir
```
is output from within `_save_multiple` method of `cutouts.py`, indicating that the method is receiving the correct value for the `output_dir` parameter. However, the line:
```
co_file=/tmp/imgdir/m13_250.417651_36.458904_100x100_astrocut.fits
```
is printing the paths (in this case, just one) in the list returned by `cutouts.fits_cut` and the path is pointing to the directory from which the image was read.

```
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.2.2, py-1.8.0, pluggy-0.13.0

Running tests with Astropy version 3.2.2.
Running tests in astrocut/tests/test_fits_output.py.

Date: 2019-10-27T22:12:47

Platform: Darwin-17.7.0-x86_64-i386-64bit

Executable: /usr/local/src/anaconda3/envs/astrocut/bin/python

Full Python Version:
3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.17.3
Scipy: 1.3.1
Matplotlib: not available
h5py: not available
Pandas: not available
astropy_helpers: 3.2.1
Using Astropy options: remote_data: none.

rootdir: /private/var/tmp/astrocut-test-u09wli0y/lib/python3.7/site-packages, inifile: setup.cfg
plugins: arraydiff-0.3, astropy-header-0.1.1, doctestplus-0.4.0, openfiles-0.4.0, remotedata-0.3.2
collected 1 item

OUTPUT_DIR=/tmp/outdir
astrocut/tests/test_fits_output.py
co_file=/tmp/imgdir/m13_250.417651_36.458904_100x100_astrocut.fits
 <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
```

**Comment by ceb8** [comment] 2019-11-06 15:01
@hickst OK, I figured out what is going on. Thanks for noticing this.

There are two related things happening (both of which need fixing) and I think one is obscuring the other.  The simplest issue is that the `fits_cut` function currently returns the file name(s) rather than the full paths. That is technically not a bug, but I think it's really confusing, so I'll update it so the full paths are returned.

The second issue is that specifically in the multiple return files case, the paths of the incoming files are not parsed properly so the entire path gets put in the "filename" which is then appended to the output directory meaning that unless the files are being read from the current directory the result is a mashup of input and output directories that doesn't exist and causes problems. And this is obscured because the returned file names just include the input directory, which reads like and incorrect but plausible full path. So that is obviously quite a major bug.

I will fix both issues and let you know when they are on master.

**Comment by hickst** [comment] 2019-11-06 18:12
@ceb8 Thanks. This will certainly help with the use case where the images are read from a read-only filesystem but the cutouts are to be written somewhere else.

**Comment by ceb8** [comment] 2019-11-15 19:42
@hickst  PR https://github.com/spacetelescope/astrocut/pull/21 resolves this issue. I haven't done a new release yet, but if you install from master your problems should be fixed.  I am going to close this issue now, please let me know if you still see these problems.

**Closed by ceb8** 2019-11-15 19:42 UTC
Labels: Priority: High, bug
